# Generated by Django 4.1.6 on 2023-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tradeModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=5)),
                ('strategy_id', models.CharField(max_length=100)),
            ],
        ),
    ]
