# Generated by Django 4.1.6 on 2023-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_trademodel_price_trademodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='price',
            field=models.FloatField(default=0,max_length=30),
                        preserve_default=False,

        ),
        migrations.AlterField(
            model_name='trademodel',
            name='quantity',
            field=models.IntegerField(default=0,max_length=30),
                        preserve_default=False,

        ),
    ]
