# Generated by Django 4.1.6 on 2023-02-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_trademodel_price_alter_trademodel_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademodel',
            options={'managed': False},
        ),
    ]
